select * from appointments 
select * from departments
select * from doctors
select * from medical_records
select * from patients

--defining pk and fk
alter table dbo.departments add primary key (department_id);
alter table dbo.patients add primary key (patient_id);
alter table dbo.doctors add primary key (doctor_id);
alter table dbo.appointments add primary key (appointment_id);
alter table dbo.medical_records add primary key (record_id);

alter table dbo.doctors
add constraint FK_departments
foreign key (department_id) references dbo.departments(department_id);

alter table dbo.appointments
add constraint FK_Appointments_Patients 
foreign key (patient_id) references dbo.patients(patient_id);

alter table dbo.appointments
add constraint FK_Appointments_Doctors 
foreign key (doctor_id) references dbo.doctors(doctor_id);

alter table dbo.medical_records
add constraint FK_MedicalRecords_Appointments 
foreign key (appointment_id) references dbo.appointments(appointment_id)
--cleaning switched genders
select count(patient_id),first_name from patients group by first_name
update patients
set gender = case
    when first_name IN ('Ali', 'Ahmed', 'Omar', 'Karim', 'Hassan', 'Youssef', 'Tarek', 'Mohamed') THEN 'Male'
    when first_name IN ('Mona', 'Hana', 'Nadia', 'Sara', 'Layla', 'Yasmin', 'Dina', 'Reem') THEN 'Female'
    else gender 
end

--1-The clinic's marketing team wants to send a campaign to insured patients in Alexandria who thier age is 30 or higher
select concat(first_name,' ',last_name) as Full_Name , phone, blood_group,
datediff(year, date_of_birth, getdate()) as Age from patients 
where city = 'Alexandria'
and insurance = 1 and datediff(year, date_of_birth, getdate()) >= 30

--2-A patient is requesting a highly experienced specialist
select full_name, years_experience from doctors where years_experience >= 15

--3-The receptionist needs to see who is coming into the clinic on a specific day
select * from appointments where appointment_date='2022-09-22' and status='Completed'

--4-Find all patients who registered in the year 2023
-- i added two rows for explaining the problem
insert into patients (patient_id, first_name, last_name, date_of_birth, gender, blood_group, city, phone, insurance, registration_date)
values ('502', 'Ahmed', 'Nehad', '2004-05-04', 'Male', 'A', 'Alexandria', '01002457847', '0', '2023-12-31 14:30:00')

insert into patients (patient_id, first_name, last_name, date_of_birth, gender, blood_group, city, phone, insurance, registration_date)
values ('501', 'Omar', 'Amir', '2004-03-04', 'Male', 'AB+', 'Alexandria', '01002457888', '1', '2024-01-01 00:00:00')

alter table patients 
alter column registration_date datetime

select patient_id,concat(first_name,' ',last_name) as Full_Name, registration_date from patients where 
registration_date between '2023-1-1' and '2023-12-31' order by registration_date desc

select patient_id,concat(first_name,' ',last_name) as Full_Name, registration_date from patients where 
registration_date between '2023-1-1' and '2024-1-1' order by registration_date desc

select patient_id,concat(first_name,' ',last_name) as Full_Name, registration_date from patients where 
registration_date >= '2023-1-1' and registration_date < '2024-1-1' order by registration_date desc

--5-Show a complete list of doctors and their department names
select dc.full_name,d.department_name from doctors dc join
departments d on dc.department_id=d.department_id

--6-Count the number of patients belonging to each blood group
select count(patient_id) number_of_patients,blood_group from patients group by blood_group

--7-Calculate total revenue generated by each doctor
select sum(a.fee_paid) as total_revenue,dc.full_name from appointments a 
join doctors dc on a.doctor_id=dc.doctor_id where a.status='Completed'
group by dc.full_name order by total_revenue desc

--8-Find the most common medical diagnoses
select top 3 diagnosis,count(diagnosis) as Total from medical_records group by diagnosis order by Total desc

--9-Identify the busiest departments based on appointment count
select d.department_name,count(a.appointment_id) as Total_appointement from departments d
join doctors as dc on d.department_id=dc.department_id
join appointments as a on dc.doctor_id=a.doctor_id group by d.department_name order by Total_appointement desc

--10-Find patients who missed their appointments ("No-Show") and have their phone numbers ready
select concat(p.first_name,' ',p.last_name) as Full_Name,p.phone,a.[status],a.appointment_date from patients as p
join appointments as a on p.patient_id=a.patient_id where [status]='No-Show' 

--11-Find doctors who have handled more than 40 appointments
select dc.full_name,count(a.appointment_id) as Total_appointment from doctors as dc
join appointments as a on dc.doctor_id=a.doctor_id group by dc.full_name having count(a.appointment_id) > 40
order by Total_appointment

--12-Get the full medical history for a patient with id = 150
select concat(p.first_name,' ',p.last_name) as Full_Name,
m.diagnosis,m.medication,m.dosage,m.duration_days from patients as p
join appointments a on p.patient_id=a.patient_id join
medical_records as m on a.appointment_id=m.appointment_id where p.patient_id=150 order by a.appointment_date desc

--13-The clinic wants a demographic breakdown without manually calculating ages
select concat(first_name,' ',last_name) as full_name, date_of_birth,
case when date_of_birth >= '2006-01-01' then 'Pediatric (Under 18)'
when date_of_birth >= '1964-01-01' then 'Adult (18-60)' else 'Senior (60+)' 
end as age_category from patients

--14- geting name and medical info for who use a mediction called 'Metformin'
--join method
select
    p.first_name, 
    p.last_name, 
    p.phone, 
    m.diagnosis,
    m.medication,
    m.notes
from patients p
join appointments a on p.patient_id = a.patient_id
join medical_records m on a.appointment_id = m.appointment_id
where m.medication like '%Met%' 
  and m.follow_up_required = '1'

  --another way and faster with CTE

  ;with TargetMedications as (
    select
        appointment_id, 
        diagnosis, 
        medication, 
        notes
    from medical_records
    where medication like '%Met%' 
      and follow_up_required = '1')
select
    p.first_name, 
    p.last_name, 
    p.phone, 
    t.diagnosis,
    t.medication,
    t.notes
from patients p
join appointments a on p.patient_id = a.patient_id
join TargetMedications t on a.appointment_id = t.appointment_id;

--15--find the most experienced doctor in each department
;with rankeddoctors as (
    select 
        dep.department_name,
        doc.full_name as doctor_name,
        doc.years_experience,
        dense_rank() over (
            partition by dep.department_name 
            order by doc.years_experience desc
        ) as experience_rank
    from doctors doc
    join departments dep on doc.department_id = dep.department_id
)
select 
        department_name, 
        doctor_name, 
        years_experience
from rankeddoctors
where experience_rank = 1

--bonus deleting duplicate 
  --inserting a duplicate raw
insert into patients (patient_id, first_name, last_name, date_of_birth, gender, blood_group, city, phone, insurance, registration_date)
values ('503', 'Ahmed', 'Nehad', '2004-05-04', 'Male', 'A', 'Alexandria', '01002457847', '0', '2023-12-31 14:30:00')

with DuplicatePatients as (
    select
        patient_id,
        first_name,
        last_name,
        row_number() over (
            partition by first_name, last_name, date_of_birth, phone 
            order by patient_id asc
        ) as row_num
    from patients
)
delete from DuplicatePatients
where row_num > 1;